# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # VM1 - hcc-master
  config.vm.define :iac_test do |iac_test|
    iac_test.vm.box = "windows10"
    iac_test.vm.provider "libvirt" do |libvirt|
      libvirt.uri = 'qemu+unix:///system'
      libvirt.driver = 'kvm'
      libvirt.host = "test1"
      libvirt.cpus = 8
      libvirt.memory = 8192
      libvirt.video_type = 'qxl'
    end
    iac_test.vm.hostname = "test1"
    iac_test.vm.network "private_network", ip: "172.168.10.100"
  end

end
